const CATEGORY_ACTION_TYPES = {
  FETCH_CATEGORIES_REQUEST: 'category/FETCH_CATEGORIES_REQUEST',
  FETCH_CATEGORIES_SUCCESS: 'category/FETCH_CATEGORIES_SUCCESS',
  FETCH_CATEGORIES_FAILED: 'category/FETCH_CATEGORIES_FAILED',
};

export default CATEGORY_ACTION_TYPES;
